name: CI Build, Test and Coverage

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    strategy:
      matrix:
        os: [ubuntu-latest]
    runs-on: ${{ matrix.os }}

    steps:
    - uses: actions/checkout@v3

    - name: Set up CMake
      uses: actions/setup-cmake@v2

    - name: Install dependencies
      run: |
        sudo apt-get update
        sudo apt-get install -y build-essential libsdl2-dev gcovr lcov

    - name: Configure with Coverage
      run: cmake -B build -DCMAKE_BUILD_TYPE=Debug -DENABLE_COVERAGE=ON

    - name: Build
      run: cmake --build build --config Debug

    - name: Run tests
      run: ctest --test-dir build --output-on-failure

    - name: Generate Coverage Report
      run: |
        cd build
        lcov --capture --directory . --output-file coverage.info
        lcov --remove coverage.info '/usr/*' '*_test.cpp' --output-file coverage.info
        lcov --list coverage.info
        genhtml coverage.info --output-directory coverage_report

    - name: Upload Coverage Report
      uses: actions/upload-artifact@v3
      with:
        name: coverage-report
        path: build/coverage_report

    - name: Upload Coverage Data
      uses: codecov/codecov-action@v3